In [1]:
import numpy as np
import POSCAR as pos
import DOS as dos

In [2]:
fe_pos = pos.POSCAR('./CONTCAR')
fe_dos = dos.DOS('./DOSCAR')

In [5]:
e = fe_dos.energies

In [6]:
e_fermi = fe_dos.e_fermi

In [7]:
fe_pos.n_ions

2

In [8]:
fe_dos.n_ions

2

In [9]:
fe_dos.spin

1

In [3]:
fe_pos.get_index('Fe')

array([0, 1])

In [12]:
fe_pos.get_index('Fe', z=[0.1,0.6])

array([1])

In [11]:
fe_dos.sum_atoms_dos(fe_pos.get_index('Fe', z=[0.1,0.6]))

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [9]:
fe_dos.get_atom_dos(fe_pos.get_index('Fe', z=[0.1,0.6])[0]).shape

(2, 1000, 9)